packages:
  # include packages in subfolders (change as required)
  - 'apps/**'
  - 'packages/**'
  # if required, exclude directories
  - '!**/test/**'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
